### ISSUE TITLE
Support Ansible that is installed with brew (not pip)

### ISSUE THREAD

**Issue by behrangsa** [h-hirokawa/atom-autocomplete-ansible#20]
I have Ansible installed on my computer using Homebrew, but the plugin is not detecting it.

**Comment by braveadmin** [comment]
Hey @behrangsa !
i figured out how to solve the problem. It's explained in the module documentation.
The module doesn't work because you have to set correct path as differs depending on installed ansible version.
You should check the actual path by running `head -1 /usr/local/bin/ansible`
After that, paste the result on the package configuration.

![image](https://user-images.githubusercontent.com/25179742/39257503-f9d46a6a-48b1-11e8-99ba-f29b9d078213.png)

Cheers!

**Comment by h-hirokawa** [comment]
Close because the workaround provided.
Thank you @braveadmin!
